sudo: required

services:
  - docker

language: python

env:
  - LANG=EN ZABBIX_VERSION=4.4 DOCKER_TAG=ubuntu-trunk
  - LANG=EN ZABBIX_VERSION=4.2 DOCKER_TAG=ubuntu-4.2-latest
  - LANG=RU ZABBIX_VERSION=4.2 DOCKER_TAG=ubuntu-4.2-latest
  - LANG=EN ZABBIX_VERSION=4.0 DOCKER_TAG=ubuntu-4.0-latest
  - LANG=RU ZABBIX_VERSION=4.0 DOCKER_TAG=ubuntu-4.0-latest
  - LANG=EN ZABBIX_VERSION=3.4 DOCKER_TAG=ubuntu-3.4-latest
  - LANG=RU ZABBIX_VERSION=3.4 DOCKER_TAG=ubuntu-3.4-latest
  - LANG=EN ZABBIX_VERSION=3.2 DOCKER_TAG=ubuntu-3.2-latest
  - LANG=RU ZABBIX_VERSION=3.2 DOCKER_TAG=ubuntu-3.2-latest
before_install:
  - python -m pip install py-zabbix
  - pushd tests/docker && docker-compose up -d
  - popd
  - pushd bin
  - while ! python check-api.py; do sleep 5; done
  - popd

install: true

script:
  - pushd bin
  - ./import-templates.py ../out/${ZABBIX_VERSION}/${LANG}/module
  - find ../out/${ZABBIX_VERSION}/${LANG}/* -type d -not -name module -exec ./import-templates.py {} \;
